# Generated by Django 5.0.6 on 2024-06-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_applications', models.CharField(blank=True, max_length=100)),
                ('logo_utilisateur', models.CharField(blank=True, max_length=100)),
                ('utilisateur', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Serveurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_serveurs', models.CharField(blank=True, max_length=100)),
                ('type_serveurs', models.CharField(blank=True, max_length=100)),
                ('nombre_processeurs', models.CharField(blank=True, max_length=100)),
                ('capacite_memoire', models.CharField(blank=True, max_length=100)),
                ('capacite_stockage', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_services', models.CharField(blank=True, max_length=100)),
                ('date_lancement', models.CharField(blank=True, max_length=100)),
                ('espace_memoire_utilise', models.CharField(blank=True, max_length=100)),
                ('memoire_vive_necessaire', models.CharField(blank=True, max_length=100)),
                ('serveur_de_lancement', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Type_serveurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_srv', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_utilisateurs', models.CharField(blank=True, max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
